Fixed the following errors:
Warning: Barriers only make sense for scanning tests on line 3096 at 1 VFIN BARRIER NOT-ADV-PCLE.
Warning: Barriers only make sense for scanning tests on line 4033 at 1 NP-HEAD-GEN OR (A Gen) OR (Num Gen) BARRIER NOT-NPMOD.
Warning: Barriers only make sense for scanning tests on line 4033 at 1 Acc BARRIER NOT-NPMODADV.
Warning: Barriers only make sense for scanning tests on line 4046 at 1 NP-HEAD-GEN OR (A Gen) OR (Num Gen) BARRIER NOT-NPMOD.
Warning: Barriers only make sense for scanning tests on line 4046 at 1 Acc BARRIER NOT-NPMODADV.
Warning: Barriers only make sense for scanning tests on line 4054 at -1 TRANS-V BARRIER NOT-NPMODADV.
Warning: Barriers only make sense for scanning tests on line 4176 at -1 ConNeg OR VFIN BARRIER WORD.
Warning: Barriers only make sense for scanning tests on line 4271 at -1 ("go" CS) BARRIER NOT-NPMOD-ACC.
Warning: Barriers only make sense for scanning tests on line 4945 at 1 go BARRIER NOT-N.
Warning: Barriers only make sense for scanning tests on line 5513 at 1C NP-HEAD-PL-NOM BARRIER PPRON-NOT-SII.
Warning: Barriers only make sense for scanning tests on line 5820 at 1 ("leat") + HAB-V-TAGS BARRIER NOT-ADV-PCLE.
Warning: Barriers only make sense for scanning tests on line 6461 at -1 COPULAS + Sg3 BARRIER REAL-V OR (N Nom) OR ADVLCASE OR MIELLA OR (A Nom) .
Warning: Barriers only make sense for scanning tests on line 7171 at 1 (N Gen) BARRIER NOT-Attr .
Warning: Barriers only make sense for scanning tests on line 7873 at 0 PrfPrc OR Inf BARRIER SV-BOUNDARY .
Warning: Barriers only make sense for scanning tests on line 7894 at 0 PrfPrc OR Inf BARRIER SV-BOUNDARY .
Warning: Barriers only make sense for scanning tests on line 7904 at 0 (PrfPrc) OR (Inf) BARRIER SV-BOUNDARY .
Warning: Barriers only make sense for scanning tests on line 8283 at 1 TIME + Gen BARRIER NOT-A .
Warning: Barriers only make sense for scanning tests on line 8538 at 0 ADVLCASE BARRIER NOT-NPMOD.
Warning: Barriers only make sense for scanning tests on line 8788 at 0 N BARRIER Loc.
Warning: Barriers only make sense for scanning tests on line 8888 at 1 N BARRIER S-BOUNDARY OR COMMA.
Warning: Barriers only make sense for scanning tests on line 8890 at 0 (Sg Com) BARRIER S-BOUNDARY OR COMMA .
Warning: Barriers only make sense for scanning tests on line 8894 at 0 (Sg Com) BARRIER S-BOUNDARY OR COMMA .
Warning: Barriers only make sense for scanning tests on line 8921 at 0 Der/Pass BARRIER NOT-NPMOD.
Warning: Barriers only make sense for scanning tests on line 8980 at 0 Acc OR Nom BARRIER SV-BOUNDARY.
Warning: Barriers only make sense for scanning tests on line 8984 at 0 Acc OR Nom BARRIER SV-BOUNDARY.
Warning: Barriers only make sense for scanning tests on line 9439 at 1C NP-HEAD-PL-NOM BARRIER PPRON-NOT-SII.

They were of two types:
a. BARRIER after absolute reference:  SELECT A IF (1 B BARRIER C) // here I added a star
b. BARRIER and LINK in wrong order: SELECT A IF (*1 B LINK 0 B BARRIER C) // here I switched order

Two rules (LocHumanAgVL, LocHuman-agentV, I was not able to reconstruct, so I commented them out.

Also two rules blocked the file form functioning, but only in Apertium
:

Warning: Position on line 5027 took many loops.
Error: Invalid position on line 5027 - caused endless loop!
(This was the rule AAttrCop, tt)

Warning: Position on line 5060 took many loops.
Error: Invalid position on line 5060 - caused endless loop!
(This was the rule AttrAdv)

Thie error here could be due to the conversion to Aperitum. Let us follow it.



git-svn-id: https://gtsvn.uit.no/langtech/trunk/gt/sme@79686 c7155fb1-f0a7-4240-a2fc-2600b6f42f90

Former-commit-id: 652fb98782aca0693f8ee8f5ad151f3d83ec16a3